import './styles.css'
import { configured, supabase } from './supabase.js'
import { signIn, signUp, signOut, sendReset, updatePassword, getSession, onAuthChange } from './auth.js'
import { getVendors, saveVendor, deactivateVendor, getEntries, upsertEntry, getMonthlyBudget, upsertMonthlyBudget, subscribeToChanges } from './data.js'

const app = document.querySelector('#app')
const months = ['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember']
const days = ['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag']
const euro = n => new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(Number(n)||0)
const number = n => new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(Number(n)||0)

let session = null
let vendors = []
let entries = []
let monthlyBudget = 0
let selectedView = 'dashboard'
let selectedYear = new Date().getFullYear()
let selectedMonth = new Date().getMonth()+1
let selectedWeek = isoWeek(new Date())
let liveChannel = null
let liveTimer = null

function toast(text) { const el=document.createElement('div');el.className='toast';el.textContent=text;document.body.append(el);setTimeout(()=>el.remove(),2600) }
function isoWeek(date){const d=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));const day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-day);const y0=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y0)/86400000)+1)/7)}
function weeksInYear(year){return isoWeek(new Date(year,11,28))}
function mondayOfWeek(year,week){const simple=new Date(year,0,1+(week-1)*7);const dow=simple.getDay();const monday=new Date(simple);monday.setDate(simple.getDate()+(dow<=4?1-dow:8-dow));return monday}
function fmtDate(d){return d.toISOString().slice(0,10)}
function monthRange(year,month){return [fmtDate(new Date(year,month-1,1)),fmtDate(new Date(year,month,0))]}
function weekDates(year,week){const start=mondayOfWeek(year,week);return days.map((name,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return{name,date:fmtDate(d)}})}
function isRateValid(rate,date){return rate.active && rate.effective_from<=date && (!rate.effective_to || rate.effective_to>=date)}
function entryCost(e){return Number(e.hours)*Number(e.vendor_rates?.hourly_rate||0)}
function totalCost(){return entries.reduce((s,e)=>s+entryCost(e),0)}
function totalHours(){return entries.reduce((s,e)=>s+Number(e.hours),0)}
function vendorTotals(){return vendors.map(v=>{const related=entries.filter(e=>e.vendor_id===v.id);return{vendor:v,hours:related.reduce((s,e)=>s+Number(e.hours),0),cost:related.reduce((s,e)=>s+entryCost(e),0)}})}

function authScreen(mode='login',message=''){
  app.innerHTML=`<main class="auth-shell"><section class="auth-card"><div class="brand"><div class="brand-mark">CP</div><div><strong>CostPilot Secure</strong><small>Geschütztes Kostencontrolling</small></div></div>${!configured?`<div class="message">Supabase ist noch nicht konfiguriert.</div>`:''}<div class="auth-tabs"><button id="tabLogin" class="${mode==='login'?'active':''}">Anmelden</button><button id="tabSignup" class="${mode==='signup'?'active':''}">Registrieren</button></div>${message?`<div class="message">${message}</div>`:''}<form id="authForm" class="form-grid">${mode==='signup'?'<label>Name<input id="fullName" required></label>':''}<label>E-Mail<input id="email" type="email" required></label><label>Passwort<input id="password" type="password" minlength="10" required></label><button class="primary" ${!configured?'disabled':''}>${mode==='login'?'Sicher anmelden':'Konto erstellen'}</button>${mode==='login'?'<button id="resetBtn" type="button" class="link-btn">Passwort vergessen?</button>':''}</form></section></main>`
  document.querySelector('#tabLogin').onclick=()=>authScreen('login');document.querySelector('#tabSignup').onclick=()=>authScreen('signup')
  document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;const result=mode==='login'?await signIn(email,password):await signUp(email,password,document.querySelector('#fullName').value.trim());if(result.error)return authScreen(mode,result.error.message);if(mode==='signup'&&!result.data.session)authScreen('login','Bitte bestätige deine E-Mail.')}
  const reset=document.querySelector('#resetBtn');if(reset)reset.onclick=async()=>{const email=document.querySelector('#email').value.trim();if(!email)return toast('Bitte E-Mail eintragen.');const{error}=await sendReset(email);toast(error?error.message:'Reset-E-Mail wurde versendet.')}
}
function passwordUpdateScreen(){app.innerHTML=`<main class="auth-shell"><section class="auth-card"><h2>Neues Passwort</h2><form id="pwForm" class="form-grid"><label>Neues Passwort<input id="newPassword" type="password" minlength="10" required></label><button class="primary">Speichern</button></form></section></main>`;document.querySelector('#pwForm').onsubmit=async e=>{e.preventDefault();const{error}=await updatePassword(document.querySelector('#newPassword').value);if(error)toast(error.message);else await loadApp()}}

function navButton(view,label){return`<button class="nav-btn ${selectedView===view?'active':''}" data-view="${view}">${label}</button>`}
function shell(){
  app.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">CP</div><div><strong>CostPilot</strong><small>Secure Cloud</small></div></div><nav>${navButton('dashboard','Übersicht')}${navButton('entry','Zeiterfassung')}${navButton('vendors','Dienstleister & Preise')}</nav><div class="sidebar-footer"><div class="user-chip">${session.user.email}<br><span class="sync-state">● Live-Synchronisierung</span></div><button id="logout" class="secondary">Abmelden</button></div></aside><main class="main"><header class="topbar"><div style="display:flex;gap:10px"><button id="menu" class="secondary mobile-menu">☰</button><div><h1 id="title"></h1><p id="subtitle"></p></div></div><div class="actions"><select id="yearSelect">${Array.from({length:9},(_,i)=>new Date().getFullYear()-4+i).map(y=>`<option ${y===selectedYear?'selected':''}>${y}</option>`).join('')}</select><select id="monthSelect">${months.map((m,i)=>`<option value="${i+1}" ${i+1===selectedMonth?'selected':''}>${m}</option>`).join('')}</select></div></header><section id="content"></section></main></div>`
  document.querySelector('#logout').onclick=()=>signOut();document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open')
  document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{selectedView=b.dataset.view;renderView();document.querySelector('.sidebar').classList.remove('open')})
  document.querySelector('#yearSelect').onchange=async e=>{selectedYear=+e.target.value;await refreshPeriod();renderView()};document.querySelector('#monthSelect').onchange=async e=>{selectedMonth=+e.target.value;await refreshPeriod();renderView()}
}

async function refreshData(){vendors=await getVendors();await refreshPeriod()}
async function refreshPeriod(){const[from,to]=monthRange(selectedYear,selectedMonth);entries=await getEntries(from,to);monthlyBudget=Number((await getMonthlyBudget(selectedYear,selectedMonth))?.amount||0)}
function renderView(){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===selectedView));const titles={dashboard:['Übersicht','Monat, Dienstleister, Kosten, Stunden und Plan auf einen Blick.'],entry:['Zeiterfassung','Alle Dienstleister gleichzeitig erfassen.'],vendors:['Dienstleister & Preise','Preiszeiträume und Firmen verwalten.']};document.querySelector('#title').textContent=titles[selectedView][0];document.querySelector('#subtitle').textContent=titles[selectedView][1];if(selectedView==='dashboard')renderDashboard();if(selectedView==='entry')renderEntry();if(selectedView==='vendors')renderVendors()}

function renderDashboard(){
  const totals=vendorTotals(),actual=totalCost(),hours=totalHours(),variance=actual-monthlyBudget,variancePct=monthlyBudget?variance/monthlyBudget*100:0,cph=hours?actual/hours:0
  const now=new Date(),isCurrent=selectedYear===now.getFullYear()&&selectedMonth===now.getMonth()+1,daysElapsed=isCurrent?now.getDate():new Date(selectedYear,selectedMonth,0).getDate(),daysMonth=new Date(selectedYear,selectedMonth,0).getDate(),forecast=isCurrent&&daysElapsed?actual/daysElapsed*daysMonth:actual
  const top=[...totals].sort((a,b)=>b.cost-a.cost)[0]
  document.querySelector('#content').innerHTML=`<div class="cards"><article class="card"><span>Ist-Kosten</span><strong>${euro(actual)}</strong><small>${months[selectedMonth-1]} ${selectedYear}</small></article><article class="card"><span>Gesamtstunden</span><strong>${number(hours)}</strong><small>${euro(cph)} je Stunde</small></article><article class="card"><span>Monatsplan</span><strong>${euro(monthlyBudget)}</strong><small class="${variance<=0?'good':'bad'}">${monthlyBudget?`${euro(Math.abs(variance))} ${variance<=0?'unter':'über'} Plan`:'Plan eintragen'}</small></article><article class="card"><span>Hochrechnung</span><strong>${euro(forecast)}</strong><small>${isCurrent?'bis Monatsende':'Monat abgeschlossen'}</small></article></div>
  <div class="grid-two"><article class="panel"><div class="panel-head"><div><h2>Monatsplan gesamt</h2><p>Ein Budget für den gesamten Monat.</p></div></div><div class="budget-row"><input id="budgetInput" type="number" min="0" step="100" value="${monthlyBudget||''}" placeholder="z. B. 25000"><button id="saveBudget" class="primary">Plan speichern</button></div><div class="stat-grid"><div><span>Abweichung</span><strong class="${variance<=0?'good':'bad'}">${euro(variance)}</strong></div><div><span>Abweichung %</span><strong class="${variance<=0?'good':'bad'}">${number(variancePct)} %</strong></div><div><span>Größter Anteil</span><strong>${top?.vendor.name||'–'}</strong></div><div><span>Aktive Firmen</span><strong>${vendors.filter(v=>v.active).length}</strong></div></div></article><article class="panel"><div class="panel-head"><div><h2>Planfortschritt</h2><p>Ist im Verhältnis zum Monatsplan</p></div></div><div class="big-progress"><span style="width:${monthlyBudget?Math.min(actual/monthlyBudget*100,100):0}%"></span></div><p><strong>${monthlyBudget?number(actual/monthlyBudget*100):0} %</strong> des Budgets verbraucht</p><p class="muted">Hochrechnung: ${euro(forecast)} · Erwartete Abweichung: ${euro(forecast-monthlyBudget)}</p></article></div>
  <article class="panel"><div class="panel-head"><div><h2>${months[selectedMonth-1]} ${selectedYear} nach Dienstleister</h2><p>Kosten, Stunden, Durchschnittssatz und Anteil.</p></div></div><div class="table-wrap"><table><thead><tr><th>Dienstleister</th><th>Stunden</th><th>Kosten</th><th>Ø Satz</th><th>Anteil</th></tr></thead><tbody>${totals.map(x=>`<tr><td><span class="dot" style="background:${x.vendor.color}"></span>${x.vendor.name}</td><td>${number(x.hours)}</td><td>${euro(x.cost)}</td><td>${euro(x.hours?x.cost/x.hours:0)}</td><td>${number(actual?x.cost/actual*100:0)} %</td></tr>`).join('')}</tbody></table></div></article>`
  document.querySelector('#saveBudget').onclick=async()=>{try{await upsertMonthlyBudget(selectedYear,selectedMonth,document.querySelector('#budgetInput').value);await refreshPeriod();renderDashboard();toast('Monatsplan gespeichert.')}catch(err){toast(err.message)}}
}

function renderEntry(){
  const active=vendors.filter(v=>v.active),dates=weekDates(selectedYear,selectedWeek)
  document.querySelector('#content').innerHTML=`<article class="panel"><div class="panel-head"><div><h2>Kalenderwoche</h2><p>Alle Firmen sind direkt sichtbar.</p></div><select id="weekSelect">${Array.from({length:weeksInYear(selectedYear)},(_,i)=>i+1).map(w=>`<option value="${w}" ${w===selectedWeek?'selected':''}>KW ${w}</option>`).join('')}</select></div><div class="all-vendors-entry">${active.map(v=>renderVendorEntry(v,dates)).join('')}</div></article>`
  document.querySelector('#weekSelect').onchange=e=>{selectedWeek=+e.target.value;renderEntry()}
  document.querySelectorAll('.hours').forEach(input=>input.onchange=async e=>{const value=Number(e.target.value.replace(',','.'))||0;try{await upsertEntry({vendor_id:e.target.dataset.vendor,rate_id:e.target.dataset.rate,work_date:e.target.dataset.date,hours:value});await refreshPeriod();renderEntry();toast('Gespeichert')}catch(err){toast(err.message)}})
}
function renderVendorEntry(vendor,dates){
  const weekRates=(vendor.vendor_rates||[]).filter(r=>dates.some(d=>isRateValid(r,d.date)))
  if(!weekRates.length)return`<section class="vendor-entry-block"><h3><span class="dot" style="background:${vendor.color}"></span>${vendor.name}</h3><p class="muted">Für diese Woche ist kein gültiger Preiszeitraum hinterlegt.</p></section>`
  const total=entries.filter(e=>e.vendor_id===vendor.id&&dates.some(d=>d.date===e.work_date)).reduce((s,e)=>s+entryCost(e),0)
  return`<section class="vendor-entry-block"><div class="vendor-entry-head"><h3><span class="dot" style="background:${vendor.color}"></span>${vendor.name}</h3><strong>${euro(total)}</strong></div><div class="entry-grid"><div class="entry-row entry-header"><div>Tag</div>${weekRates.map(r=>`<div>${r.name}<br><small>${euro(r.hourly_rate)}/h</small></div>`).join('')}<div>Kosten</div></div>${dates.map(d=>{const cells=weekRates.map(r=>{if(!isRateValid(r,d.date))return'<div class="rate-unavailable">–</div>';const existing=entries.find(e=>e.work_date===d.date&&e.vendor_id===vendor.id&&e.rate_id===r.id);return`<input class="hours" data-date="${d.date}" data-vendor="${vendor.id}" data-rate="${r.id}" inputmode="decimal" value="${existing?.hours||''}" placeholder="0,00">`}).join('');const dayCost=entries.filter(e=>e.work_date===d.date&&e.vendor_id===vendor.id).reduce((s,e)=>s+entryCost(e),0);return`<div class="entry-row"><div class="day">${d.name}<br><small>${d.date.split('-').reverse().join('.')}</small></div>${cells}<div>${euro(dayCost)}</div></div>`}).join('')}</div></section>`
}

function periodLabel(r){const from=r.effective_from?.split('-').reverse().join('.')||'–',to=r.effective_to?r.effective_to.split('-').reverse().join('.'):'offen';return`${from} – ${to}`}
function renderVendors(){
  document.querySelector('#content').innerHTML=`<article class="panel"><div class="panel-head"><div><h2>Firmen und Preiszeiträume</h2><p>Preisänderungen werden als eigener Zeitraum gespeichert.</p></div><button id="newVendor" class="primary">+ Dienstleister</button></div><div class="vendor-list">${vendors.map(v=>`<div class="vendor-card"><div><strong><span class="dot" style="background:${v.color}"></span>${v.name}</strong>${!v.active?' <span class="badge employee">Inaktiv</span>':''}<div class="price-history">${(v.vendor_rates||[]).sort((a,b)=>b.effective_from.localeCompare(a.effective_from)).map(r=>`<div class="price-period"><span><strong>${r.name}</strong> · ${euro(r.hourly_rate)}/h</span><small>${periodLabel(r)}</small></div>`).join('')}</div></div><div class="actions"><button class="secondary editVendor" data-id="${v.id}">Bearbeiten</button>${v.active?`<button class="danger disableVendor" data-id="${v.id}">Deaktivieren</button>`:''}</div></div>`).join('')}</div></article>`
  document.querySelector('#newVendor').onclick=()=>vendorModal();document.querySelectorAll('.editVendor').forEach(b=>b.onclick=()=>vendorModal(vendors.find(v=>v.id===b.dataset.id)));document.querySelectorAll('.disableVendor').forEach(b=>b.onclick=async()=>{if(confirm('Dienstleister deaktivieren?')){await deactivateVendor(b.dataset.id);await refreshData();renderVendors()}})
}
function rateRow(r={}){return`<div class="rate-period-row"><input class="rName" data-id="${r.id||''}" value="${r.name||''}" placeholder="Tätigkeit" required><input class="rPrice" type="number" min="0" step=".01" value="${r.hourly_rate||''}" placeholder="€/h" required><label>Von<input class="rFrom" type="date" value="${r.effective_from||`${selectedYear}-01-01`}" required></label><label>Bis<input class="rTo" type="date" value="${r.effective_to||''}"></label></div>`}
function vendorModal(vendor=null){const rates=vendor?.vendor_rates?.length?vendor.vendor_rates:[{}],modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<form class="modal-card wide-modal"><h2>${vendor?'Dienstleister bearbeiten':'Dienstleister anlegen'}</h2><label>Firmenname<input id="vName" value="${vendor?.name||''}" required></label><label>Farbe<input id="vColor" type="color" value="${vendor?.color||'#2563eb'}"></label><h3>Preise und Gültigkeitszeiträume</h3><div id="rates">${rates.map(rateRow).join('')}</div><button id="addRate" type="button" class="secondary">+ Neuer Preiszeitraum</button><div class="modal-actions"><button id="cancel" type="button" class="secondary">Abbrechen</button><button class="primary">Speichern</button></div></form>`;document.body.append(modal);modal.querySelector('#cancel').onclick=()=>modal.remove();modal.querySelector('#addRate').onclick=()=>modal.querySelector('#rates').insertAdjacentHTML('beforeend',rateRow());modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const rates=[...modal.querySelectorAll('.rate-period-row')].map(row=>({id:row.querySelector('.rName').dataset.id||undefined,name:row.querySelector('.rName').value.trim(),hourly_rate:Number(row.querySelector('.rPrice').value),effective_from:row.querySelector('.rFrom').value,effective_to:row.querySelector('.rTo').value||null}));try{await saveVendor({id:vendor?.id,name:modal.querySelector('#vName').value.trim(),color:modal.querySelector('#vColor').value,active:true,rates});modal.remove();await refreshData();renderVendors();toast('Gespeichert.')}catch(err){toast(err.message)}}}

async function loadApp(){await refreshData();shell();renderView();if(liveChannel)supabase.removeChannel(liveChannel);liveChannel=subscribeToChanges(()=>{clearTimeout(liveTimer);liveTimer=setTimeout(async()=>{await refreshData();renderView();toast('Daten synchronisiert')},350)})}
async function boot(){if(!configured){authScreen();return}const{data}=await getSession();session=data.session;onAuthChange(async(event,newSession)=>{session=newSession;if(event==='PASSWORD_RECOVERY')return passwordUpdateScreen();if(!session)authScreen();else await loadApp()});if(session)await loadApp();else authScreen()}
boot().catch(err=>authScreen('login',err.message))
